# Generated by Django 6.0.6 on 2026-07-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobanalysis',
            options={'verbose_name_plural': 'Job Analyses'},
        ),
    ]
